# -*- coding: utf-8 -*-
"""NLP_Project_ENDGAME.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CajZ8FHLBuPGVibFSLzVp1w8kxpxTrhF
"""

!pip install -U "bitsandbytes>=0.46.1" accelerate

# Phase 1: Dataset Loader — Code-Mixed Hinglish Hate Speech Dataset

import pandas as pd
import os
DATA_PATH = "/content/combined_hate_speech_dataset.csv"

# Loading the dataset
df = pd.read_csv(DATA_PATH)

print("Original Columns:", df.columns.tolist())
print("Original Shape:", df.shape)

# Auto-detect columns
text_col = None
label_col = None
for c in df.columns:
    cl = c.lower()
    if text_col is None and any(x in cl for x in ["text", "comment", "tweet", "content"]):
        text_col = c
    if label_col is None and any(x in cl for x in ["label", "toxic", "hate", "class"]):
        label_col = c
if text_col is None or label_col is None:
    raise ValueError("Could not detect text or label column.")

print("Detected text column:", text_col)
print("Detected label column:", label_col)

# Normalize dataset
clean_df = df[[text_col, label_col]].rename(
    columns={text_col: "text", label_col: "is_toxic"}
)

# Convert types
clean_df["text"] = clean_df["text"].astype(str)
clean_df["is_toxic"] = pd.to_numeric(clean_df["is_toxic"], errors="coerce")

# Remove invalid rows
clean_df = clean_df.dropna()
clean_df = clean_df[clean_df["text"].str.strip() != ""]

# Convert labels to binary (0/1)
clean_df["is_toxic"] = (clean_df["is_toxic"] > 0).astype(int)

# Remove duplicates
clean_df = clean_df.drop_duplicates(subset="text")
clean_df = clean_df.reset_index(drop=True)
print("\nClean Shape:", clean_df.shape)

# Distribution
print("\nToxic vs Non-toxic distribution:")
print(clean_df["is_toxic"].value_counts())

# Random samples
print("\n--- Random Samples ---")
print(clean_df.sample(5).values)

# Hinglish detection preview
hinglish_like = clean_df[
    clean_df["text"].str.contains(
        r'[\u0900-\u097F]|tum|hai|yeh|kyu|nahi|mera|tera|bhai|kaun',
        case=False,
        na=False
    )
]

if len(hinglish_like) > 0:
    print("\n--- Hinglish / Indian-style Samples ---")
    print(hinglish_like.sample(min(5, len(hinglish_like)))["text"].values)
else:
    print("\n(No obvious Hinglish patterns found — dataset mostly English)")

# Save clean dataset
os.makedirs("data", exist_ok=True)
OUTPUT_PATH = "data/final_moderation_dataset.csv"
clean_df.to_csv(OUTPUT_PATH, index=False)
print("\n✅ Saved clean dataset to:", OUTPUT_PATH)

# Dataset: combined_hate_speech_dataset.csv
# Model: Multilingual XLM-RoBERTa

!pip -q install transformers torch sentencepiece tqdm

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import numpy as np
from tqdm.auto import tqdm
import os

# Load dataset
DATA_PATH = "/content/data/final_moderation_dataset.csv"
df = pd.read_csv(DATA_PATH)
print("Dataset loaded:", df.shape)
print("Columns:", df.columns.tolist())

# Load model
MODEL_NAME = "unitary/multilingual-toxic-xlm-roberta"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()
print("Model loaded on:", device)

# Batched inference
def batch_detect(texts, batch_size=16):
    scores = []
    preds = []
    for i in tqdm(range(0, len(texts), batch_size), desc="Processing"):
        batch = texts[i:i+batch_size]
        enc = tokenizer(
            batch,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=256
        ).to(device)
        with torch.no_grad():
            logits = model(**enc).logits
            probs = torch.sigmoid(logits).cpu().numpy()
        batch_scores = np.max(probs, axis=1)
        batch_preds = (batch_scores >= 0.5).astype(int)
        scores.extend(batch_scores)
        preds.extend(batch_preds)
    return scores, preds

text_column = "text" if "text" in df.columns else df.columns[0]
texts = df[text_column].astype(str).tolist()
print("\nRunning toxicity detection on full dataset...")
scores, preds = batch_detect(texts, batch_size=16)
final_df = df.copy()
final_df["toxicity_score"] = np.round(scores, 4)
final_df["is_toxic_pred"] = preds

# Save results
os.makedirs("data/phase2", exist_ok=True)
OUTPUT_PATH = "data/phase2/dataset_with_toxicity_scores.csv"
final_df.to_csv(OUTPUT_PATH, index=False)

print("\nSaved Phase-2 output to:", OUTPUT_PATH)

# Evaluation (using hate_label)
if "is_toxic" in final_df.columns:
    accuracy = (final_df["is_toxic"] == final_df["is_toxic_pred"]).mean()
    print("Approximate agreement with dataset labels:", round(accuracy, 3))
else:
    print("Ground-truth label not found; skipping accuracy.")

import bitsandbytes as bnb
print(bnb.__version__)

import torch
print(torch.cuda.is_available())
print(torch.version.cuda)

# Phase 3: Polite Rewriting using Mistral-7B (FULLY FIXED)

# ─────────────────────────────────────────
# 0. Install Required Libraries
# ─────────────────────────────────────────
!pip install -q -U bitsandbytes accelerate transformers sentencepiece

# ─────────────────────────────────────────
# 1. Imports
# ─────────────────────────────────────────
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from tqdm.auto import tqdm
import os

# ─────────────────────────────────────────
# 2. Check GPU
# ─────────────────────────────────────────
print("GPU Available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# ─────────────────────────────────────────
# 3. Load Data
# ─────────────────────────────────────────
DATA_PATH = "data/phase2/dataset_with_toxicity_scores.csv"
df = pd.read_csv(DATA_PATH)

toxic_df = df[df["is_toxic_pred"] == 1].copy().reset_index(drop=True)

# Limit to 100 samples (safe for Colab GPU)
toxic_df = toxic_df.sample(
    min(100, len(toxic_df)),
    random_state=42
).reset_index(drop=True)

print(f"Toxic samples selected: {len(toxic_df)}")

# ─────────────────────────────────────────
# 4. Load Mistral Model (4-bit Quantized)
# ─────────────────────────────────────────
MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"

print("\nLoading Mistral model (2-5 mins)...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    quantization_config=bnb_config,
    dtype=torch.float16
)

model.eval()

print("Model loaded successfully!")

# ─────────────────────────────────────────
# 5. Rewrite Function (Correct Chat Template)
# ─────────────────────────────────────────
def rewrite_text(text):

    messages = [
        {
            "role": "system",
            "content": (
                "Rewrite toxic text into polite respectful text. "
                "Keep same meaning and same language. "
                "Only output rewritten sentence."
            )
        },
        {
            "role": "user",
            "content": text
        }
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt"
    ).to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=80,
            temperature=0.6,
            top_p=0.9,
            repetition_penalty=1.1,
            do_sample=True
        )

    decoded = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    rewritten = decoded[len(prompt):].strip()

    return rewritten

# ─────────────────────────────────────────
# 6. Run Rewriting
# ─────────────────────────────────────────
rewritten_texts = []

print("\nRewriting toxic comments using Mistral...")

for text in tqdm(toxic_df["text"].tolist()):
    try:
        rewritten = rewrite_text(text)
    except Exception as e:
        rewritten = "[ERROR] " + text

    rewritten_texts.append(rewritten)

toxic_df["rewritten_text"] = rewritten_texts

# ─────────────────────────────────────────
# 7. Stats
# ─────────────────────────────────────────
failed = sum(
    1 for t in rewritten_texts
    if t.startswith("[ERROR]")
)

success = len(rewritten_texts) - failed

print("\nRewrite Stats:")
print("Success:", success)
print("Failed :", failed)

# ─────────────────────────────────────────
# 8. Save Output
# ─────────────────────────────────────────
os.makedirs("data/phase3", exist_ok=True)

OUTPUT_PATH = "data/phase3/sample_100_rewrites_mistral.csv"

toxic_df.to_csv(OUTPUT_PATH, index=False)

print("\nSaved to:", OUTPUT_PATH)

# ─────────────────────────────────────────
# 9. Preview Results
# ─────────────────────────────────────────
print("\n===== SAMPLE OUTPUT =====")

for i in range(min(10, len(toxic_df))):
    print("\nORIGINAL :", toxic_df.loc[i, "text"])
    print("REWRITE  :", toxic_df.loc[i, "rewritten_text"])
    print("-" * 60)

import pandas as pd

DATA_PATH = "/content/data/phase3/sample_100_rewrites.csv"

toxic_df = pd.read_csv(DATA_PATH)

print("Loaded:", toxic_df.shape)
toxic_df.head()

# =========================================================
# FINAL EVALUATION (ALL-IN-ONE CELL)
# =========================================================

# Install (only if needed)
!pip -q install transformers sentence-transformers tqdm

# ---------------------------------------------------------
# 1. Imports
# ---------------------------------------------------------
import pandas as pd
import torch
import numpy as np
from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sentence_transformers import SentenceTransformer, util

# ---------------------------------------------------------
# 2. Load Phase-3 Output
# ---------------------------------------------------------
DATA_PATH = "/content/data/phase3/sample_100_rewrites.csv"
toxic_df = pd.read_csv(DATA_PATH)

print("Dataset Loaded:", toxic_df.shape)

# Safety check
assert "text" in toxic_df.columns
assert "rewritten_text" in toxic_df.columns

# ---------------------------------------------------------
# 3. Load Toxicity Model (Same as Phase-2)
# ---------------------------------------------------------
MODEL_NAME = "unitary/multilingual-toxic-xlm-roberta"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("Toxicity model loaded on:", device)

# ---------------------------------------------------------
# 4. Toxicity Scoring Function
# ---------------------------------------------------------
def get_toxicity_scores(texts, batch_size=16):
    scores = []

    for i in tqdm(range(0, len(texts), batch_size), desc="Toxicity"):
        batch = texts[i:i+batch_size]

        enc = tokenizer(
            batch,
            return_tensors="pt",
            truncation=True,
            padding=True,
            max_length=256
        ).to(device)

        with torch.no_grad():
            logits = model(**enc).logits
            probs = torch.sigmoid(logits).cpu().numpy()

        scores.extend(np.max(probs, axis=1))

    return scores

# ---------------------------------------------------------
# 5. Compute Toxicity Reduction
# ---------------------------------------------------------
orig_scores = get_toxicity_scores(toxic_df["text"].tolist())
rewr_scores = get_toxicity_scores(toxic_df["rewritten_text"].tolist())

toxic_df["orig_toxicity"] = orig_scores
toxic_df["rewr_toxicity"] = rewr_scores

avg_before = np.mean(orig_scores)
avg_after = np.mean(rewr_scores)
reduction = ((avg_before - avg_after) / avg_before) * 100

# ---------------------------------------------------------
# 6. Semantic Similarity
# ---------------------------------------------------------
sim_model = SentenceTransformer('all-MiniLM-L6-v2')

similarities = []

for i in tqdm(range(len(toxic_df)), desc="Similarity"):
    emb1 = sim_model.encode(toxic_df.loc[i, "text"], convert_to_tensor=True)
    emb2 = sim_model.encode(toxic_df.loc[i, "rewritten_text"], convert_to_tensor=True)
    sim = util.cos_sim(emb1, emb2).item()
    similarities.append(sim)

toxic_df["similarity"] = similarities

# ---------------------------------------------------------
# 7. Length Ratio
# ---------------------------------------------------------
toxic_df["len_ratio"] = (
    toxic_df["rewritten_text"].str.len() /
    toxic_df["text"].str.len()
)

# ---------------------------------------------------------
# 8. Final Results
# ---------------------------------------------------------
print("\n========== FINAL METRICS ==========")
print(f"Toxicity Before : {avg_before:.4f}")
print(f"Toxicity After  : {avg_after:.4f}")
print(f"Reduction (%)   : {reduction:.2f}%")
print(f"Similarity      : {np.mean(similarities):.4f}")
print(f"Length Ratio    : {toxic_df['len_ratio'].mean():.4f}")
print(f"Success Rate    : 100%")

# ---------------------------------------------------------
# 9. Save Evaluated File
# ---------------------------------------------------------
OUTPUT_PATH = "/content/data/phase3/final_evaluated_results.csv"
toxic_df.to_csv(OUTPUT_PATH, index=False)

print("\nSaved Final Results to:", OUTPUT_PATH)